### ISSUE TITLE
syncSvc.createOrMigrateDatabase errors

### ISSUE THREAD

**Issue by barbalex** [vlcn-io/cr-sqlite#273]
I am experimenting with cr-sqlite to build an application with it.

I followed the docs to scaffold an app (https://vlcn.io/docs/js/first-app).

Somehow I can't seem to get it to sync via the server.

After starting this error appears:
```
SqliteError: Could not update table infos
    at Database.prepare (/mnt/c/Users/alexa/capturing_vlcn/node_modules/.pnpm/better-sqlite3@8.4.0/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at new DB (file:///mnt/c/Users/alexa/capturing_vlcn/node_modules/.pnpm/@vlcn.io+direct-connect-nodejs@0.4.0/node_modules/@vlcn.io/direct-connect-nodejs/dist/private/DB.js:37:43)
    at DBCache.getStr (file:///mnt/c/Users/alexa/capturing_vlcn/node_modules/.pnpm/@vlcn.io+direct-connect-nodejs@0.4.0/node_modules/@vlcn.io/direct-connect-nodejs/dist/private/DBCache.js:41:17)
    at DBCache.get (file:///mnt/c/Users/alexa/capturing_vlcn/node_modules/.pnpm/@vlcn.io+direct-connect-nodejs@0.4.0/node_modules/@vlcn.io/direct-connect-nodejs/dist/private/DBCache.js:34:21)
    at SyncService.createOrMigrateDatabase (file:///mnt/c/Users/alexa/capturing_vlcn/node_modules/.pnpm/@vlcn.io+direct-connect-nodejs@0.4.0/node_modules/@vlcn.io/direct-connect-nodejs/dist/SyncService.js:48:33)
    at file:///mnt/c/Users/alexa/capturing_vlcn/server.js:71:31
    at file:///mnt/c/Users/alexa/capturing_vlcn/server.js:131:13
    at Layer.handle [as handle_request] (/mnt/c/Users/alexa/capturing_vlcn/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/layer.js:95:5)
    at next (/mnt/c/Users/alexa/capturing_vlcn/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/mnt/c/Users/alexa/capturing_vlcn/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/route.js:114:3) {
  code: 'SQLITE_ERROR'
}
Sourcemap for "/mnt/c/Users/alexa/capturing_vlcn/node_modules/.pnpm/@vlcn.io+rx-tbl@0.12.0/node_modules/@vlcn.io/rx-tbl/dist/index.js" points to missing source files
Sourcemap for "/mnt/c/Users/alexa/capturing_vlcn/node_modules/.pnpm/@vlcn.io+rx-tbl@0.12.0/node_modules/@vlcn.io/rx-tbl/dist/tblrx.js" points to missing source files
Sourcemap for "/mnt/c/Users/alexa/capturing_vlcn/node_modules/.pnpm/@vlcn.io+xplat-api@0.12.0/node_modules/@vlcn.io/xplat-api/dist/xplat-api.js" points to missing source files
```

`at file:///mnt/c/Users/alexa/capturing_vlcn/server.js:71:31` points to the `syncSvc.createOrMigrateDatabase(msg)
` call inside server.js.

Trying to debug it, I altered the code inside server.js from:
```js
app.post(
  '/sync/create-or-migrate',
  makeSafe(async (req, res) => {
    const msg = serializer.decode(req.body)
    const ret = await syncSvc.createOrMigrateDatabase(msg)
    res.json(serializer.encode(ret))
  })
```
to:
```js
app.post(
  '/sync/create-or-migrate',
  makeSafe(async (req, res) => {
    const msg = serializer.decode(req.body)
    console.log('create-or-migrate, msg:', msg)
    let ret
    try {
      ret = await syncSvc.createOrMigrateDatabase(msg)
    } catch (error) {
      console.log('create-or-migrate, error from createOrMigrateDatabase:', ret)
    }
    console.log('create-or-migrate, ret:', ret)
    res.json(serializer.encode(ret))
  })
```
This changes the log to:
```
create-or-migrate, msg: {
  _tag: 7,
  dbid: Uint8Array(16) [
    209,  83, 109, 167, 255,
    236,  73,  82, 170,  59,
     85, 182,  18, 210, 250,
    135
  ],
  requestorDbid: Uint8Array(16) [
     40, 187,  31, 203, 253,
    198,  75, 170, 175, 180,
     90, 230,  11, 146,  38,
    131
  ],
  schemaName: 'main',
  schemaVersion: -5178240011179864021n
}
create-or-migrate, error from createOrMigrateDatabase: undefined
create-or-migrate, ret: undefined
TypeError: Cannot read properties of undefined (reading '_tag')
    at encode (file:///mnt/c/Users/alexa/capturing_vlcn/node_modules/.pnpm/@vlcn.io+direct-connect-common@0.4.0/node_modules/@vlcn.io/direct-connect-common/dist/msg/jsonEncode.js:9:17)
    at JsonSerializer.encode (file:///mnt/c/Users/alexa/capturing_vlcn/node_modules/.pnpm/@vlcn.io+direct-connect-common@0.4.0/node_modules/@vlcn.io/direct-connect-common/dist/msg/JsonSerializer.js:14:25)
    at file:///mnt/c/Users/alexa/capturing_vlcn/server.js:73:25
    at file:///mnt/c/Users/alexa/capturing_vlcn/server.js:131:13
    at Layer.handle [as handle_request] (/mnt/c/Users/alexa/capturing_vlcn/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/layer.js:95:5)
    at next (/mnt/c/Users/alexa/capturing_vlcn/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/mnt/c/Users/alexa/capturing_vlcn/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/mnt/c/Users/alexa/capturing_vlcn/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/layer.js:95:5)
    at /mnt/c/Users/alexa/capturing_vlcn/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/mnt/c/Users/alexa/capturing_vlcn/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/index.js:346:12)
```
So it seems that `await syncSvc.createOrMigrateDatabase(msg)` returns `undefined` which then leads to `res.json(serializer.encode(ret))` to fail.

I work on Windows 11. But installed and started the application inside ubuntu on Windows wsl because it would not work otherwise.

Please tell me if you need more info.

**Comment by tantaman** [comment]
That is pretty strange. Windows does usually need some special care though.

I pushed some updates so it works on windows w/o WSL.

If you clone `git clone https://github.com/vlcn-io/vite-starter.git my-project` and checkout the `dev` branch it should work on windows but still with one windows specific bug I'm trying to figure out: the server isn't pushing update events to the client so clients have to refresh (or poll) to get the latest changes :(


```
PS C:\Users\tantaman\workspace> git clone https://github.com/vlcn-io/vite-starter.git my-project
Cloning into 'my-project'...
remote: Enumerating objects: 451, done.
remote: Counting objects: 100% (184/184), done.
remote: Compressing objects: 100% (86/86), done.
remote: Total 451 (delta 103), reused 150 (delta 87), pack-reused 267
Receiving objects: 100% (451/451), 1.04 MiB | 10.96 MiB/s, done.
Resolving deltas: 100% (259/259), done.
PS C:\Users\tantaman\workspace> cd my-project
PS C:\Users\tantaman\workspace\my-project> git checkout dev
Switched to a new branch 'dev'
branch 'dev' set up to track 'origin/dev'.
PS C:\Users\tantaman\workspace\my-project> pnpm install
Lockfile is up to date, resolution step is skipped
Packages: +568
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: C:\Users\tantaman\AppData\Local\pnpm\store\v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 568, reused 568, downloaded 0, added 568, done

dependencies:
+ @vlcn.io/crsqlite-wasm 0.14.0-next.0
+ @vlcn.io/direct-connect-browser 0.4.0-next.1
+ @vlcn.io/direct-connect-common 0.5.0-next.1
+ @vlcn.io/direct-connect-nodejs 0.5.0-next.3
+ @vlcn.io/react 2.4.0-next.1
+ @vlcn.io/rx-tbl 0.13.0-next.0
+ @vlcn.io/xplat-api 0.13.0-next.0
+ cors 2.8.5
+ express 4.18.2
+ react 18.2.0
+ react-dom 18.2.0

devDependencies:
+ @types/react 18.0.28
+ @types/react-dom 18.0.11
+ @typescript-eslint/eslint-plugin 5.57.1
+ @typescript-eslint/parser 5.57.1
+ @vitejs/plugin-react 4.0.0
+ eslint 8.38.0
+ eslint-plugin-react-hooks 4.6.0
+ eslint-plugin-react-refresh 0.3.4
+ typescript 5.0.2
+ vite 4.3.2
+ vite-plugin-pwa 0.16.4

Done in 7.2s
PS C:\Users\tantaman\workspace\my-project> pnpm dev

> vlcn-vite-starter@0.0.0 dev C:\Users\tantaman\workspace\my-project
> node ./slurp.mjs && node ./server.js --dev

src\schemas\main.mjs
Pat: dbs/*
Server listening at http://localhost:8080
Start outbound stream

  VITE v4.3.2  ready in 1021 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
Close outbound stream
Sourcemap for "C:/Users/tantaman/workspace/my-project/node_modules/.pnpm/@vlcn.io+rx-tbl@0.13.0-next.0/node_modules/@vlcn.io/rx-tbl/dist/index.js" points to missing source files
Sourcemap for "C:/Users/tantaman/workspace/my-project/node_modules/.pnpm/@vlcn.io+rx-tbl@0.13.0-next.0/node_modules/@vlcn.io/rx-tbl/dist/tblrx.js" points to missing source files
Sourcemap for "C:/Users/tantaman/workspace/my-project/node_modules/.pnpm/@vlcn.io+xplat-api@0.13.0-next.0/node_modules/@vlcn.io/xplat-api/dist/xplat-api.js" points to missing source files
Start outbound stream
Start outbound stream
```

**Comment by tantaman** [comment]
The root of your original problem is this error: `SqliteError: Could not update table infos`

Could you attach of a copy of your server database?

**Comment by tantaman** [comment]
Ok, that last bug is fixed on windows now. Give it a spin from powershell and it should all work for you.

```ps
PS C:\Users\tantaman\workspace> pnpm create "@vlcn.io" my-app2
.../Local/pnpm/store/v3/tmp/dlx-10992    |   +3 +
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: C:\Users\tantaman\AppData\Local\pnpm\store\v3
  Virtual store is at:             AppData/Local/pnpm/store/v3/tmp/dlx-10992/node_modules/.pnpm
.../Local/pnpm/store/v3/tmp/dlx-10992    | Progress: resolved 3, reused 3, downloaded 0, added 3, done
downloading https://github.com/vlcn-io/vite-starter/archive/c77d8df267741c96aa9b32c58f7d8846b0274e8f.tar.gz to C:\Users\tantaman\.degit\github\vlcn-io\vite-starter/c77d8df267741c96aa9b32c58f7d8846b0274e8f.tar.gz
extracting C:\Users\tantaman\.degit\github\vlcn-io\vite-starter/c77d8df267741c96aa9b32c58f7d8846b0274e8f.tar.gz to my-app2
cloned vlcn-io/vite-starter#HEAD to my-app2

� Your project has been successfully created! �

Next steps:
  - cd my-app2
  - npm install
  - npm run dev

PS C:\Users\tantaman\workspace> cd my-app2
PS C:\Users\tantaman\workspace\my-app2> pnpm install
Lockfile is up to date, resolution step is skipped
Packages: +568
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: C:\Users\tantaman\AppData\Local\pnpm\store\v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 568, reused 568, downloaded 0, added 568, done

dependencies:
+ @vlcn.io/crsqlite-wasm 0.14.0-next.0
+ @vlcn.io/direct-connect-browser 0.4.0-next.1
+ @vlcn.io/direct-connect-common 0.5.0-next.1
+ @vlcn.io/direct-connect-nodejs 0.5.0-next.6
+ @vlcn.io/react 2.4.0-next.1
+ @vlcn.io/rx-tbl 0.13.0-next.0
+ @vlcn.io/xplat-api 0.13.0-next.0
+ cors 2.8.5
+ express 4.18.2
+ react 18.2.0
+ react-dom 18.2.0

devDependencies:
+ @types/react 18.0.28
+ @types/react-dom 18.0.11
+ @typescript-eslint/eslint-plugin 5.57.1
+ @typescript-eslint/parser 5.57.1
+ @vitejs/plugin-react 4.0.0
+ eslint 8.38.0
+ eslint-plugin-react-hooks 4.6.0
+ eslint-plugin-react-refresh 0.3.4
+ typescript 5.0.2
+ vite 4.3.2
+ vite-plugin-pwa 0.16.4

Done in 9.1s
PS C:\Users\tantaman\workspace\my-app2> pnpm run dev

> my-app2@0.0.0 dev C:\Users\tantaman\workspace\my-app2
> node ./slurp.mjs && node ./server.js --dev

src\schemas\main.mjs
Pat: dbs/*
Server listening at http://localhost:8080

  VITE v4.3.2  ready in 1072 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
Sourcemap for "C:/Users/tantaman/workspace/my-app2/node_modules/.pnpm/@vlcn.io+rx-tbl@0.13.0-next.0/node_modules/@vlcn.io/rx-tbl/dist/index.js" points to missing source files
Sourcemap for "C:/Users/tantaman/workspace/my-app2/node_modules/.pnpm/@vlcn.io+rx-tbl@0.13.0-next.0/node_modules/@vlcn.io/rx-tbl/dist/tblrx.js" points to missing source files
Sourcemap for "C:/Users/tantaman/workspace/my-app2/node_modules/.pnpm/@vlcn.io+xplat-api@0.13.0-next.0/node_modules/@vlcn.io/xplat-api/dist/xplat-api.js" points to missing source files
Start outbound stream
Start outbound stream
Close outbound stream
```

Opened that up on my windows box (http://localhost:5173/) and everything was syncing as expected. LMK how it goes for you.

**Comment by barbalex** [comment]
@tantaman 
Installing by using `pnpm create "@vlcn.io" my-app2` worked fine. Does not break any more on powershell.
And now the issue disappeared as well 🎆 

Thank's a lot!

And by the way: This is a GREAT project, exactly what I need to create really nice offline capable apps. Such a treat to be able to use SQLite and sync using CRDT's.

If it works well for me it will revolutionize the way I build apps.

**Comment by tantaman** [comment]
Thanks! There’s still a lot to do though. Like permission rules, letting a
server overrule changes, multi-tenant databases :) getting there though.

**Comment by barbalex** [comment]
Yeah, I can see quite a bit of work coming up for you. 
Looking forward to the results!

Not sure I have completely understood how this (the existing parts) will all work for my use case but I will hammer at it for a while now.

**Comment by barbalex** [comment]
I now managed to adapt my existing project to work with your changes and it works well on windows now too 😄
