### ISSUE TITLE
Load extension error on Windows

### ISSUE THREAD

**Issue by c6p** [vlcn-io/cr-sqlite#286]
Load extension fails with prebuilt binary from releases. I've tried both v0.14.0 and v0.13.0 `dll`s.

```python
import sqlite3
 
conn = sqlite3.connect("tmp.db")
conn.enable_load_extension(True)
conn.load_extension("crsqlite.dll")**
```

```cmd
> python test.py
Traceback (most recent call last):
  File "C:\Users\can.altiparmak\Downloads\test.py", line 6, in <module>
    conn.load_extension('crsqlite.dll')
sqlite3.OperationalError: Belirtilen modül bulunamadı.
```

Same with rust.
```rust
    let conn = Connection::open_in_memory()?;

    unsafe {
        let _guard = LoadExtensionGuard::new(&conn)?;
        conn.load_extension("crsqlite.dll", Some("sqlite3_crsqlite_init"))?
    }
```

```cmd
Running `target\debug\rusqlite-test.exe`
Error: SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some("Belirtilen modül bulunamadı.\r\n"))
error: process didn't exit successfully: `target\debug\rusqlite-test.exe` (exit code: 1)
```

While I can load other extension successfully, such as the ones from [sqlean](https://github.com/nalgeon/sqlean/releases).

Windows 10 x64 22H2
Python 3.10.10

**Comment by tantaman** [comment]
This is what I just tried this morning on Windows:

```shell
C:\Users\tantaman>python
Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> conn = sqlite3.connect("tmp.db")
>>> conn.enable_load_extension(True)
>>> conn.load_extension("./crsqlite")
>>> conn.execute("SELECT crsql_siteid()").fetchall()
[(b'\xb1F\x95\x99\xaa\xd0@M\xa7\xcb\x8d\xe9L%&\xea',)]
>>>
```

w/ 0.14.0

I also re-enabled Windows in GitHub CI and those tests seem to be working --

https://github.com/vlcn-io/cr-sqlite/actions/runs/5599462745/jobs/10240455790

**Comment by c6p** [comment]
Thanks for the quick response.

Tried on another machine, same. I'll try to build myself later, and report back.
```cmd
PS C:\Users\can\Desktop> python
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> conn = sqlite3.connect("tmp.db")
>>> conn.enable_load_extension(True)
>>> conn.load_extension("./crsqlite")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
sqlite3.OperationalError: The specified module could not be found.
```

**Comment by tantaman** [comment]
hm. The fact that it says `The specified module could not be found` seems like the path to the extension is wrong.

Can you link the output of `dir`, before running python?

**Comment by c6p** [comment]
Sorry for late answer.

```cmd
PS C:\Users\can.altiparmak\Desktop\test> dir

    Directory: C:\Users\can.altiparmak\Desktop\test

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          18.07.2023    11:22        1708514 crsqlite.dll
-a---          19.07.2023    09:41        1634351 crsqlite.dll-13
-a---          18.07.2023    17:45         777198 sqlean.dll

PS C:\Users\can.altiparmak\Desktop\test> python
Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> conn = sqlite3.connect("tmp.db")
>>> conn.enable_load_extension(True)
>>> conn.load_extension("./crsqlite")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
sqlite3.OperationalError: Belirtilen modül bulunamadı.

>>> conn.load_extension("./sqlean")
>>> conn.execute("SELECT crsql_siteid()").fetchall()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
sqlite3.OperationalError: no such function: crsql_siteid
>>> conn.execute("SELECT * FROM sqlean_define").fetchall()
[]
>>>
```

Though, `so` load fine in WSL. Is there anything I can provide?

**Comment by tantaman** [comment]
This should be fixed now.

See this release: https://github.com/vlcn-io/cr-sqlite/releases/tag/prebuild-test.zip

which includes new windows builds.

Note that v0.16 is not compatible with v0.15 DBs.

**Comment by c6p** [comment]
Thank you @tantaman for your work. It loads fine now.
